name = "PlayingCards"
uuid = "ecfe714a-bcc2-4d11-ad00-25525ff8f984"
authors = ["Charles Kawczynski <kawczynski.charles@gmail.com>"]
version = "0.4.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.34"
julia = "1.5"
